### PR TITLE
4.3.x

### LINKED ISSUE #163: Script start with full screen browser then exit and continue running normal
**Describe the bug**
Script start running with full screen browser then exit and continue running normal

**To Reproduce**
1. Just run any script

**Expected behavior**
Script start running with maximum screen browser.

**Screenshots**
Snapshot 2020-07-12 12 23 14

[allure-results 1.zip](https://github.com/MohabMohie/SHAFT_ENGINE/files/4908436/allure-results.1.zip)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 83.0.4103.116 (Official Build) (32-bit)

### LINKED ISSUE #172: Watermark is not displayed on screenshots or GIFs
the images are stored without any watermark

### LINKED ISSUE #173: Update allure report to use the new shaft logo
Update allure report to use the new shaft logo

### PR DESCRIPTION
**Pull request by MohabMohie**
logo and read-me face lift
closes #163 
closes #172
closes #173

### CODE REVIEW

File: src/main/java/com/shaft/cucumber/ElementSteps.java [hunk 1]
```diff
@@ -18,27 +17,27 @@ public ElementSteps(ThreadLocal<WebDriver> driver) {
         }
     }
 
-    protected static By getLocatorFromTypeAndValue(LocatorType type, String locatorValue) {
-        switch (type) {
-            case ID -> {
+    protected static By getLocatorFromTypeAndValue(String locatorType, String locatorValue) {
+        switch (locatorType.toLowerCase()) {
```
Comment (MohabMohie) [inline src/main/java/com/shaft/cucumber/ElementSteps.java:21]: Codacy found an issue: [Switch statements should have a default label](https://app.codacy.com/manual/mohab.mohieeldeen/SHAFT_ENGINE/pullRequest?prid=5909418)

**Comment by MohabMohie** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity decreasing per file
==============================
+ src/main/java/com/shaft/gui/browser/BrowserActions.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mohab.mohieeldeen/SHAFT_ENGINE/pullRequest?prid=5909418&bid=19358838)

File: src/main/java/com/shaft/cucumber/ElementSteps.java [hunk 2]
```diff
@@ -18,27 +17,27 @@ public ElementSteps(ThreadLocal<WebDriver> driver) {
         }
     }
 
-    protected static By getLocatorFromTypeAndValue(LocatorType type, String locatorValue) {
-        switch (type) {
-            case ID -> {
+    protected static By getLocatorFromTypeAndValue(String locatorType, String locatorValue) {
```
Comment (MohabMohie) [inline src/main/java/com/shaft/cucumber/ElementSteps.java:20]: Codacy found an issue: [The method 'getLocatorFromTypeAndValue(String, String)' has an NPath complexity of 2147483647](https://app.codacy.com/manual/mohab.mohieeldeen/SHAFT_ENGINE/pullRequest?prid=5909418)

**Comment by MohabMohie** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity decreasing per file
==============================
+ src/main/java/com/shaft/gui/browser/BrowserActions.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/mohab.mohieeldeen/SHAFT_ENGINE/pullRequest?prid=5909418&bid=19358838)
